from Mapper import Mapper
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QApplication,QFileDialog,QTableWidgetItem
import sys
from Extractor import Extractor

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.mapper = Mapper()
        self.result = Extractor()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 320)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("medic2-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Adobe Naskh Medium")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.mainMap = QtWidgets.QPushButton(self.tab)
        self.mainMap.setObjectName("mainMap")
        self.horizontalLayout_8.addWidget(self.mainMap)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.about = QtWidgets.QPushButton(self.tab)
        self.about.setObjectName("about")
        self.horizontalLayout_9.addWidget(self.about)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.icdSearch = QtWidgets.QPushButton(self.tab_2)
        self.icdSearch.setObjectName("icdSearch")
        self.gridLayout_2.addWidget(self.icdSearch, 1, 1, 1, 1)
        self.diseaseSearch = QtWidgets.QPushButton(self.tab_2)
        self.diseaseSearch.setObjectName("diseaseSearch")
        self.gridLayout_2.addWidget(self.diseaseSearch, 2, 1, 1, 1)
        self.addButt = QtWidgets.QPushButton(self.tab_2)
        self.addButt.setObjectName("addButt")
        self.gridLayout_2.addWidget(self.addButt, 3, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 4, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cancel1 = QtWidgets.QPushButton(self.page_2)
        self.cancel1.setObjectName("cancel1")
        self.verticalLayout_3.addWidget(self.cancel1)
        self.cancel2 = QtWidgets.QPushButton(self.page_2)
        self.cancel2.setObjectName("cancel2")
        self.verticalLayout_3.addWidget(self.cancel2)
        self.cancel3 = QtWidgets.QPushButton(self.page_2)
        self.cancel3.setObjectName("cancel3")
        self.verticalLayout_3.addWidget(self.cancel3)
        self.cancel4 = QtWidgets.QPushButton(self.page_2)
        self.cancel4.setObjectName("cancel4")
        self.verticalLayout_3.addWidget(self.cancel4)
        self.cancel5 = QtWidgets.QPushButton(self.page_2)
        self.cancel5.setObjectName("cancel5")
        self.verticalLayout_3.addWidget(self.cancel5)
        self.cancel6 = QtWidgets.QPushButton(self.page_2)
        self.cancel6.setObjectName("cancel6")
        self.verticalLayout_3.addWidget(self.cancel6)
        self.cancel7 = QtWidgets.QPushButton(self.page_2)
        self.cancel7.setObjectName("cancel7")
        self.verticalLayout_3.addWidget(self.cancel7)
        self.cancel8 = QtWidgets.QPushButton(self.page_2)
        self.cancel8.setObjectName("cancel8")
        self.verticalLayout_3.addWidget(self.cancel8)
        self.cancel9 = QtWidgets.QPushButton(self.page_2)
        self.cancel9.setObjectName("cancel9")
        self.verticalLayout_3.addWidget(self.cancel9)
        self.cancel10 = QtWidgets.QPushButton(self.page_2)
        self.cancel10.setObjectName("cancel10")
        self.verticalLayout_3.addWidget(self.cancel10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prev = QtWidgets.QPushButton(self.page_2)
        self.prev.setObjectName("prev")
        self.horizontalLayout_3.addWidget(self.prev)
        self.next = QtWidgets.QPushButton(self.page_2)
        self.next.setObjectName("next")
        self.horizontalLayout_3.addWidget(self.next)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.page_2)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.page_3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.table2 = QtWidgets.QTableWidget(self.page_3)
        self.table2.setObjectName("table2")
        self.table2.setColumnCount(0)
        self.table2.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.table2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Edit4 = QtWidgets.QPushButton(self.page_3)
        self.Edit4.setObjectName("Edit4")
        self.gridLayout_3.addWidget(self.Edit4, 3, 0, 1, 1)
        self.Edit7 = QtWidgets.QPushButton(self.page_3)
        self.Edit7.setObjectName("Edit7")
        self.gridLayout_3.addWidget(self.Edit7, 6, 0, 1, 1)
        self.Edit6 = QtWidgets.QPushButton(self.page_3)
        self.Edit6.setObjectName("Edit6")
        self.gridLayout_3.addWidget(self.Edit6, 5, 0, 1, 1)
        self.Edit2 = QtWidgets.QPushButton(self.page_3)
        self.Edit2.setObjectName("Edit2")
        self.gridLayout_3.addWidget(self.Edit2, 1, 0, 1, 1)
        self.Edit8 = QtWidgets.QPushButton(self.page_3)
        self.Edit8.setObjectName("Edit8")
        self.gridLayout_3.addWidget(self.Edit8, 7, 0, 1, 1)
        self.Edit3 = QtWidgets.QPushButton(self.page_3)
        self.Edit3.setObjectName("Edit3")
        self.gridLayout_3.addWidget(self.Edit3, 2, 0, 1, 1)
        self.Edit9 = QtWidgets.QPushButton(self.page_3)
        self.Edit9.setObjectName("Edit9")
        self.gridLayout_3.addWidget(self.Edit9, 8, 0, 1, 1)
        self.Edit10 = QtWidgets.QPushButton(self.page_3)
        self.Edit10.setObjectName("Edit10")
        self.gridLayout_3.addWidget(self.Edit10, 9, 0, 1, 1)
        self.Edit1 = QtWidgets.QPushButton(self.page_3)
        self.Edit1.setObjectName("Edit1")
        self.gridLayout_3.addWidget(self.Edit1, 0, 0, 1, 1)
        self.Edit5 = QtWidgets.QPushButton(self.page_3)
        self.Edit5.setObjectName("Edit5")
        self.gridLayout_3.addWidget(self.Edit5, 4, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.prevmap = QtWidgets.QPushButton(self.page_3)
        self.prevmap.setObjectName("prevmap")
        self.horizontalLayout_4.addWidget(self.prevmap)
        self.nextmap = QtWidgets.QPushButton(self.page_3)
        self.nextmap.setObjectName("nextmap")
        self.horizontalLayout_4.addWidget(self.nextmap)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.finish = QtWidgets.QPushButton(self.page_3)
        self.finish.setObjectName("finish")
        self.horizontalLayout_4.addWidget(self.finish)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.abouttext = QtWidgets.QTextBrowser(self.page_4)
        self.abouttext.setObjectName("abouttext")
        self.verticalLayout_9.addWidget(self.abouttext)
        self.back = QtWidgets.QPushButton(self.page_4)
        self.back.setObjectName("back")
        self.verticalLayout_9.addWidget(self.back)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icdback = QtWidgets.QPushButton(self.page_5)
        self.icdback.setObjectName("icdback")
        self.horizontalLayout.addWidget(self.icdback)
        self.lineEdit = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.icdsearch = QtWidgets.QPushButton(self.page_5)
        self.icdsearch.setObjectName("icdsearch")
        self.horizontalLayout.addWidget(self.icdsearch)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.icdtable = QtWidgets.QTableWidget(self.page_5)
        self.icdtable.setObjectName("icdtable")
        self.icdtable.setColumnCount(0)
        self.icdtable.setRowCount(0)
        self.verticalLayout_10.addWidget(self.icdtable)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.disback = QtWidgets.QPushButton(self.page_6)
        self.disback.setObjectName("disback")
        self.horizontalLayout_10.addWidget(self.disback)
        self.dissearchline = QtWidgets.QLineEdit(self.page_6)
        self.dissearchline.setObjectName("dissearchline")
        self.horizontalLayout_10.addWidget(self.dissearchline)
        self.dissearch = QtWidgets.QPushButton(self.page_6)
        self.dissearch.setObjectName("dissearch")
        self.horizontalLayout_10.addWidget(self.dissearch)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.distable = QtWidgets.QTableWidget(self.page_6)
        self.distable.setObjectName("distable")
        self.distable.setColumnCount(0)
        self.distable.setRowCount(0)
        self.verticalLayout_12.addWidget(self.distable)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.disnext = QtWidgets.QPushButton(self.page_6)
        self.disnext.setObjectName("disnext")
        self.horizontalLayout_14.addWidget(self.disnext)
        self.disprev = QtWidgets.QPushButton(self.page_6)
        self.disprev.setObjectName("disprev")
        self.horizontalLayout_14.addWidget(self.disprev)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem16)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.label_2 = QtWidgets.QLabel(self.page_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.addicdline = QtWidgets.QLineEdit(self.page_7)
        self.addicdline.setObjectName("addicdline")
        self.horizontalLayout_11.addWidget(self.addicdline)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem19)
        self.label_3 = QtWidgets.QLabel(self.page_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.adddisline = QtWidgets.QLineEdit(self.page_7)
        self.adddisline.setObjectName("adddisline")
        self.horizontalLayout_12.addWidget(self.adddisline)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem20)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem21)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem22)
        self.addbuttonBox = QtWidgets.QDialogButtonBox(self.page_7)
        self.addbuttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.addbuttonBox.setObjectName("addbuttonBox")
        self.verticalLayout_14.addWidget(self.addbuttonBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout.addWidget(self.stackedWidget)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.mainMap.clicked.connect(self.secondpage)
        self.finish.clicked.connect(self.firstpage)
        self.buttonBox.accepted.connect(self.lastpage)
        self.buttonBox.rejected.connect(self.firstpage)
        self.about.clicked.connect(self.aboutpage)
        self.back.clicked.connect(self.firstpage)
        self.icdSearch.clicked.connect(self.icdsearchpage)
        self.icdback.clicked.connect(self.firstpage)
        self.icdsearch.clicked.connect(self.icdsearchfunc)
        self.disback.clicked.connect(self.firstpage)
        self.diseaseSearch.clicked.connect(self.dissearchpage)
        self.addButt.clicked.connect(self.addpage)
        self.addbuttonBox.accepted.connect(self.addfunc)
        self.addbuttonBox.rejected.connect(self.firstpage)
        self.dissearch.clicked.connect(self.dissearchfunc)
        self.prev.clicked.connect(self.tab1funcp)
        self.next.clicked.connect(self.tab1funcn)
        self.prevmap.clicked.connect(self.tab2funcp)
        self.nextmap.clicked.connect(self.tab2funcn)
        self.disprev.clicked.connect(self.tabdisfuncn)##disnext
        self.disnext.clicked.connect(self.tabdisfuncp)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def lastpage(self):
        self.stackedWidget.setCurrentIndex(2)
        diagnosis = ['anemia', 'mumps polyneuropathy', 'ross river', 'plasmodium malariae malaria nephropathy']
        code = self.mapper.map(diagnosis)
        for icd in code:
            icd = ''.join(icd)
            rowPosition = self.table2.rowCount()
            self.table2.insertRow(rowPosition)
            self.table2.setItem(rowPosition,0,QTableWidgetItem("file"))
            self.table2.setItem(rowPosition, 1, QTableWidgetItem(diagnosis[rowPosition]))
            self.table2.setItem(rowPosition, 2, QTableWidgetItem(icd[rowPosition]))
            self.table2.setItem(rowPosition, 3, QTableWidgetItem("X"))



    def firstpage(self):
        self.stackedWidget.setCurrentIndex(0)
    def secondpage(self):
        self.stackedWidget.setCurrentIndex(1)
        self.openFileNamesDialog()
    def aboutpage(self):
        self.stackedWidget.setCurrentIndex(3)
    def icdsearchpage(self):
        self.stackedWidget.setCurrentIndex(4)
    def icdsearchfunc(self):
        pass
    def dissearchpage(self):
        self.stackedWidget.setCurrentIndex(5)
    def dissearchfunc(self):
        pass
    def addpage(self):
        self.stackedWidget.setCurrentIndex(6)
    def addfunc(self):
        pass
    def tab1funcn(self):
        pass
    def tab1funcp(self):
        pass
    def tab2funcn(self):
        pass
    def tab2funcp(self):
        pass
    def tabdisfuncn(self):
        pass
    def tabdisfuncp(self):
        pass

    def openFileNamesDialog(self):
        options = QFileDialog.Options()

        options |= QFileDialog.DontUseNativeDialog
        files, _ = QFileDialog.getOpenFileNames(self, "QFileDialog.getOpenFileNames()", "",
                                            "All Files (*);;Python Files (*.py)", options=options)
        ans = self.result.getalldiagnosis()
        print(ans)
        '''
        if files:
            for path in files:
                path = ''.join(path)
                print(path[path.rfind('/') + 1:])
                '''

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ICD-10 Code MApper"))
        self.label.setText(_translate("MainWindow", "ICD-10 Code Mapper"))
        self.mainMap.setText(_translate("MainWindow", "Mapping"))
        self.about.setText(_translate("MainWindow", "About"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Mapping"))
        self.icdSearch.setText(_translate("MainWindow", "ICD Code"))
        self.diseaseSearch.setText(_translate("MainWindow", "Disease"))
        self.addButt.setText(_translate("MainWindow", "ADD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Others"))
        self.cancel1.setText(_translate("MainWindow", "Cancel"))
        self.cancel2.setText(_translate("MainWindow", "Cancel"))
        self.cancel3.setText(_translate("MainWindow", "Cancel"))
        self.cancel4.setText(_translate("MainWindow", "Cancel"))
        self.cancel5.setText(_translate("MainWindow", "Cancel"))
        self.cancel6.setText(_translate("MainWindow", "Cancel"))
        self.cancel7.setText(_translate("MainWindow", "Cancel"))
        self.cancel8.setText(_translate("MainWindow", "Cancel"))
        self.cancel9.setText(_translate("MainWindow", "Cancel"))
        self.cancel10.setText(_translate("MainWindow", "Cancel"))
        self.prev.setText(_translate("MainWindow", "Prev"))
        self.next.setText(_translate("MainWindow", "Next"))
        self.Edit4.setText(_translate("MainWindow", "Edit"))
        self.Edit7.setText(_translate("MainWindow", "Edit"))
        self.Edit6.setText(_translate("MainWindow", "Edit"))
        self.Edit2.setText(_translate("MainWindow", "Edit"))
        self.Edit8.setText(_translate("MainWindow", "Edit"))
        self.Edit3.setText(_translate("MainWindow", "Edit"))
        self.Edit9.setText(_translate("MainWindow", "Edit"))
        self.Edit10.setText(_translate("MainWindow", "Edit"))
        self.Edit1.setText(_translate("MainWindow", "Edit"))
        self.Edit5.setText(_translate("MainWindow", "Edit"))
        self.prevmap.setText(_translate("MainWindow", "Prev"))
        self.nextmap.setText(_translate("MainWindow", "Next"))
        self.finish.setText(_translate("MainWindow", "Finish"))
        self.abouttext.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.1pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Our mission is to </span><span style=\" font-size:18pt; font-weight:600; color:#55aaff;\">organise</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">the </span><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">information</span><span style=\" font-size:18pt; font-weight:600;\"> and make</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">it </span><span style=\" font-size:18pt; font-weight:600; color:#00aa00;\">universally accessible</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">and </span><span style=\" font-size:18pt; font-weight:600; color:#ffaa00;\">useful</span><span style=\" font-size:18pt; font-weight:600; color:#000000;\">.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p></body></html>"))
        self.back.setText(_translate("MainWindow", "Back"))
        self.label_4.setText(_translate("MainWindow", "ICD-10 Code:"))
        self.icdback.setText(_translate("MainWindow", "Back"))
        self.icdsearch.setText(_translate("MainWindow", "Search"))
        self.label_5.setText(_translate("MainWindow", "Disease:"))
        self.disback.setText(_translate("MainWindow", "Back"))
        self.dissearch.setText(_translate("MainWindow", "Search"))
        self.disnext.setText(_translate("MainWindow", "Prev"))
        self.disprev.setText(_translate("MainWindow", "Next"))
        self.label_6.setText(_translate("MainWindow", "Modify Database:"))
        self.label_2.setText(_translate("MainWindow", "ICD Code"))
        self.label_3.setText(_translate("MainWindow", "Disease   "))


app = QApplication(sys.argv)
w = Ui_MainWindow()
w.show()
sys.exit(app.exec_())

