from maaaap import Mapper
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QMainWindow, QApplication, QFileDialog, QTableWidgetItem
import sys
from Extractor import Extractor


class Thread(QThread):
    update = pyqtSignal(str, list, str, float)
    fin = pyqtSignal()

    def __init__(self, files, ans, parent=None):
        super(Thread, self).__init__(parent)
        self.files = files
        self.ans = ans

    def __del__(self):
        self.wait()

    def run(self):
        i = 1
        n = len(self.files)
        for j in range(n):
            complete = i * 100 / n
            i = i + 1
            path = self.files[j]
            path = ''.join(path)
            diag = self.ans[self.files[j]]
            print(diag)
            bre = -1
            di = ""
            for co in diag:
                re = co.find("?")
                if re != -1:
                    bre = re
                    di = co
            if bre != -1:
                diag.remove(di)
                diag.append(di[:bre])
            print(diag)
            mapping = Mapper()
            code = mapping.map(diag)
            print([x[1] for x in code])
            item = ','.join(diag)
            self.update.emit(path, code, item, complete)
        self.fin.emit()


class Ui_MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/medic2-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.page)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Adobe Naskh Medium")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.mainMap = QtWidgets.QPushButton(self.tab)
        self.mainMap.setObjectName("mainMap")
        self.horizontalLayout_8.addWidget(self.mainMap)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.about = QtWidgets.QPushButton(self.tab)
        self.about.setObjectName("about")
        self.horizontalLayout_9.addWidget(self.about)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.icdSearch = QtWidgets.QPushButton(self.tab_2)
        self.icdSearch.setObjectName("icdSearch")
        self.gridLayout_2.addWidget(self.icdSearch, 1, 1, 1, 1)
        self.diseaseSearch = QtWidgets.QPushButton(self.tab_2)
        self.diseaseSearch.setObjectName("diseaseSearch")
        self.gridLayout_2.addWidget(self.diseaseSearch, 2, 1, 1, 1)
        self.addButt = QtWidgets.QPushButton(self.tab_2)
        self.addButt.setObjectName("addButt")
        self.gridLayout_2.addWidget(self.addButt, 3, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 4, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(23)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.page_2)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.page_3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.table2 = QtWidgets.QTableWidget(self.page_3)
        self.table2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table2.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed)
        self.table2.setRowCount(0)
        self.table2.setObjectName("table2")
        self.table2.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table2.setHorizontalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table2.setHorizontalHeaderItem(3, item)
        self.table2.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_6.addWidget(self.table2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.fincancel = QtWidgets.QPushButton(self.page_3)
        self.fincancel.setEnabled(True)
        self.fincancel.setDefault(True)
        self.fincancel.setFlat(False)
        self.fincancel.setObjectName("fincancel")
        self.horizontalLayout_4.addWidget(self.fincancel)
        self.finish = QtWidgets.QPushButton(self.page_3)
        self.finish.setEnabled(False)
        self.finish.setObjectName("finish")
        self.horizontalLayout_4.addWidget(self.finish)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.abouttext = QtWidgets.QTextBrowser(self.page_4)
        self.abouttext.setObjectName("abouttext")
        self.verticalLayout_9.addWidget(self.abouttext)
        self.back = QtWidgets.QPushButton(self.page_4)
        self.back.setDefault(True)
        self.back.setObjectName("back")
        self.verticalLayout_9.addWidget(self.back)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icdback = QtWidgets.QPushButton(self.page_5)
        self.icdback.setObjectName("icdback")
        self.horizontalLayout.addWidget(self.icdback)
        self.lineEdit = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.icdsearch = QtWidgets.QPushButton(self.page_5)
        self.icdsearch.setDefault(True)
        self.icdsearch.setObjectName("icdsearch")
        self.horizontalLayout.addWidget(self.icdsearch)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.icdtable = QtWidgets.QTableWidget(self.page_5)
        self.icdtable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.icdtable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.icdtable.setObjectName("icdtable")
        self.icdtable.setColumnCount(2)
        self.icdtable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.icdtable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.icdtable.setHorizontalHeaderItem(1, item)
        self.icdtable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.icdtable)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.disback = QtWidgets.QPushButton(self.page_6)
        self.disback.setObjectName("disback")
        self.horizontalLayout_10.addWidget(self.disback)
        self.dissearchline = QtWidgets.QLineEdit(self.page_6)
        self.dissearchline.setObjectName("dissearchline")
        self.horizontalLayout_10.addWidget(self.dissearchline)
        self.dissearch = QtWidgets.QPushButton(self.page_6)
        self.dissearch.setDefault(True)
        self.dissearch.setObjectName("dissearch")
        self.horizontalLayout_10.addWidget(self.dissearch)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.distable = QtWidgets.QTableWidget(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distable.sizePolicy().hasHeightForWidth())
        self.distable.setSizePolicy(sizePolicy)
        self.distable.setAutoFillBackground(False)
        self.distable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.distable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.distable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.distable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.distable.setTabKeyNavigation(False)
        self.distable.setProperty("showDropIndicator", False)
        self.distable.setDragDropOverwriteMode(False)
        self.distable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.distable.setRowCount(0)
        self.distable.setColumnCount(2)
        self.distable.setObjectName("distable")
        item = QtWidgets.QTableWidgetItem()
        self.distable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.distable.setHorizontalHeaderItem(1, item)
        self.distable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_12.addWidget(self.distable)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.label_2 = QtWidgets.QLabel(self.page_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.addicdline = QtWidgets.QLineEdit(self.page_7)
        self.addicdline.setObjectName("addicdline")
        self.horizontalLayout_11.addWidget(self.addicdline)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.verticalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.label_3 = QtWidgets.QLabel(self.page_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.adddisline = QtWidgets.QLineEdit(self.page_7)
        self.adddisline.setObjectName("adddisline")
        self.horizontalLayout_12.addWidget(self.adddisline)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem19)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem20)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem21)
        self.addbuttonBox = QtWidgets.QDialogButtonBox(self.page_7)
        self.addbuttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.addbuttonBox.setObjectName("addbuttonBox")
        self.verticalLayout_14.addWidget(self.addbuttonBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.mainMap.clicked.connect(self.secondpage)
        self.finish.clicked.connect(self.firstpage)
        self.buttonBox.accepted.connect(self.lastpage)
        self.buttonBox.rejected.connect(self.firstpage)
        self.about.clicked.connect(self.aboutpage)
        self.back.clicked.connect(self.firstpage)
        self.icdSearch.clicked.connect(self.icdsearchpage)
        self.icdback.clicked.connect(self.firstpage)
        self.icdsearch.clicked.connect(self.icdsearchfunc)
        self.disback.clicked.connect(self.firstpage)
        self.diseaseSearch.clicked.connect(self.dissearchpage)
        self.addButt.clicked.connect(self.addpage)
        self.addbuttonBox.accepted.connect(self.addfunc)
        self.addbuttonBox.rejected.connect(self.firstpage)
        self.dissearch.clicked.connect(self.dissearchfunc)
        self.fincancel.clicked.connect(self.firstpage)
        self.finish.clicked.connect(self.firstpage)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def firstpage(self):
        self.finish.setEnabled(False)
        self.stackedWidget.setCurrentIndex(0)

    def secondpage(self):
        self.openFileNamesDialog()
        self.tableWidget.setRowCount(0)
        if self.files:
            for path in self.files:
                path = ''.join(path)
                rowPosition = self.tableWidget.rowCount()
                self.tableWidget.insertRow(rowPosition)
                self.tableWidget.setItem(rowPosition, 0, QTableWidgetItem(path[path.rfind('/') + 1:]))
                self.tableWidget.setItem(rowPosition, 1, QTableWidgetItem("X"))
        self.stackedWidget.setCurrentIndex(1)

    def lastpage(self):
        self.progressBar.setValue(0)
        self.table2.setRowCount(0)
        self.stackedWidget.setCurrentIndex(2)
        self.finish.setEnabled(False)
        code = ['Small anal fissure', 'Hepatitis B', 'Coronary artery disease']
        self.threadclass = Thread(self.files, self.ans)
        self.threadclass.start()
        self.threadclass.update.connect(self.lastpageupdate)
        self.threadclass.fin.connect(self.lastfin)

    def lastfin(self):
        self.finish.setEnabled(True)
        self.threadclass.terminate()

    def lastpageupdate(self, path, code, item, complete):
        rowPosition = self.table2.rowCount()
        self.table2.insertRow(rowPosition)
        self.table2.setItem(rowPosition, 0, QTableWidgetItem(path[path.rfind('/') + 1:]))
        self.table2.setItem(rowPosition, 1, QTableWidgetItem(item))
        self.table2.setItem(rowPosition, 2, QTableWidgetItem(','.join([x[1] for x in code])))
        self.progressBar.setValue(complete)

    def aboutpage(self):
        self.stackedWidget.setCurrentIndex(3)

    def icdsearchpage(self):
        self.stackedWidget.setCurrentIndex(4)

    def icdsearchfunc(self):
        pass

    def dissearchpage(self):
        self.stackedWidget.setCurrentIndex(5)

    def dissearchfunc(self):
        pass

    def addpage(self):
        self.stackedWidget.setCurrentIndex(6)

    def addfunc(self):
        pass

    def openFileNamesDialog(self):
        # options = QFileDialog.Options()
        #
        # options |= QFileDialog.DontUseNativeDialog
        self.files, _ = QFileDialog.getOpenFileNames(self, "QFileDialog.getOpenFileNames()", "",
                                                     "All Files (*);;Python Files (*.py)")  # , options=options)
        print(self.files)
        self.result = Extractor(self.files)
        self.ans = self.result.getalldiagnosis()
        print(self.ans)
        if self.files:
            for path in self.files:
                path = ''.join(path)
                print(path[path.rfind('/') + 1:])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ICD-10 Code MApper"))
        self.label.setText(_translate("MainWindow", "ICD-10 Code Mapper"))
        self.mainMap.setText(_translate("MainWindow", "Mapping"))
        self.about.setText(_translate("MainWindow", "About"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Mapping"))
        self.icdSearch.setText(_translate("MainWindow", "ICD Code"))
        self.diseaseSearch.setText(_translate("MainWindow", "Disease"))
        self.addButt.setText(_translate("MainWindow", "ADD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Others"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.table2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.table2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Diagnosis"))
        item = self.table2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ICD-10 Code"))
        self.fincancel.setText(_translate("MainWindow", "Cancel"))
        self.finish.setText(_translate("MainWindow", "Finish"))
        self.abouttext.setHtml(_translate("MainWindow",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.1pt; font-weight:400; font-style:normal;\">\n"
                                          "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                          "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p>\n"
                                          "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p>\n"
                                          "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p>\n"
                                          "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Our mission is to </span><span style=\" font-size:18pt; font-weight:600; color:#55aaff;\">organise</span></p>\n"
                                          "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">the </span><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">information</span><span style=\" font-size:18pt; font-weight:600;\"> and make</span></p>\n"
                                          "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">it </span><span style=\" font-size:18pt; font-weight:600; color:#00aa00;\">universally accessible</span></p>\n"
                                          "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">and </span><span style=\" font-size:18pt; font-weight:600; color:#ffaa00;\">useful</span><span style=\" font-size:18pt; font-weight:600; color:#000000;\">.</span></p>\n"
                                          "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p>\n"
                                          "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; font-weight:600;\"><br /></p></body></html>"))
        self.back.setText(_translate("MainWindow", "Back"))
        self.label_4.setText(_translate("MainWindow", "ICD-10 Code:"))
        self.icdback.setText(_translate("MainWindow", "Back"))
        self.icdsearch.setText(_translate("MainWindow", "Search"))
        item = self.icdtable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ICD-10 Code"))
        item = self.icdtable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Disease"))
        self.label_5.setText(_translate("MainWindow", "Disease:"))
        self.disback.setText(_translate("MainWindow", "Back"))
        self.dissearch.setText(_translate("MainWindow", "Search"))
        item = self.distable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Disease"))
        item = self.distable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ICD-10 Code"))
        self.label_6.setText(_translate("MainWindow", "Modify Database:"))
        self.label_2.setText(_translate("MainWindow", "ICD Code"))
        self.label_3.setText(_translate("MainWindow", "Disease   "))


app = QApplication(sys.argv)
w = Ui_MainWindow()
w.show()
sys.exit(app.exec_())
